apiVersion: v1
kind: Service
metadata:
  labels:
  k8s-app: exoplanetapp
  name: exoplanetapp
  namespace: exoplanetapp
spec:
  type: NodePort
  ports:
  - port: 5000
  selector:
  k8s-app: exoplanetapp
